encoding: utf-8

plugins:
    - jekyll-regex-replace

# SEO相关信息
title: FJdarc Blog
description: FJdarc的个人博客
keywords: FJdarc,Blog,C/C++,C#,Rust
author: FJdarc
footerText: "Copyright © 2026 FJdarc"

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
    auto_ids: true
    input: GFM
    syntax_highlighter: rouge
exclude:
    [
        "CNAME",
        "README.md",
        "LICENSE",
        "_site",
        "dist",
        "Gemfile",
        "Gemfile.lock",
        "blog.sh",
        "vendor",
    ]

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: "https://fjdarc.github.io/"
baseurl: ""

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl:

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开
menu:
    - title: 首页
      url: /
    - title: 归类
      url: /pages/categories.html
    - title: 搜索
      url: /pages/search.html
    - title: 小说
      url: /pages/novels.html
    # - title: 友链
    #   url: /pages/links.html
    # - title: 留言
    #   url: /pages/chat.html
    - title: 关于
      url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
    - title: TMaize Blog
      url: https://blog.tmaize.net

# 小说
novels:
    - name: 末日时在做什么？有没有空？可以来拯救吗？
      author: 枯野瑛
      chapter: ["01", "02", "03", "04", "05", "EX"]
    - name: 无职转生 ～到了异世界就拿出真本事～
      author: 理不尽な孫の手
      chapter:
          [
              "01",
              "02",
              "03",
              "04",
              "05",
              "06",
              "07",
              "08",
              "09",
              "10",
              "11",
              "12",
              "13",
              "14",
              "15",
              "16",
              "17",
              "18",
              "19",
              "20",
              "21",
              "22",
              "23",
              "24",
              "25",
              "26",
          ]
